// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzVUxhqRyvonHc8gzgkhvRPKKOZ2pbF6k',
    appId: '1:323366878871:web:c0300a2db4089d4784b3d2',
    messagingSenderId: '323366878871',
    projectId: 'todo-notes-app-debe3',
    authDomain: 'todo-notes-app-debe3.firebaseapp.com',
    storageBucket: 'todo-notes-app-debe3.appspot.com',
    measurementId: 'G-YQ1FMZ455L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXfM-7E89mlekeT5vzCZIuF2oKbzoS87s',
    appId: '1:323366878871:android:d3675a30341bf46284b3d2',
    messagingSenderId: '323366878871',
    projectId: 'todo-notes-app-debe3',
    storageBucket: 'todo-notes-app-debe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzI1L53gOI1V3FFtCw_F3fdyRxd5qAxDI',
    appId: '1:323366878871:ios:e13aa89d0353fd2984b3d2',
    messagingSenderId: '323366878871',
    projectId: 'todo-notes-app-debe3',
    storageBucket: 'todo-notes-app-debe3.appspot.com',
    iosBundleId: 'com.example.todooo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzI1L53gOI1V3FFtCw_F3fdyRxd5qAxDI',
    appId: '1:323366878871:ios:e13aa89d0353fd2984b3d2',
    messagingSenderId: '323366878871',
    projectId: 'todo-notes-app-debe3',
    storageBucket: 'todo-notes-app-debe3.appspot.com',
    iosBundleId: 'com.example.todooo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzVUxhqRyvonHc8gzgkhvRPKKOZ2pbF6k',
    appId: '1:323366878871:web:2f08ccc5b041a23384b3d2',
    messagingSenderId: '323366878871',
    projectId: 'todo-notes-app-debe3',
    authDomain: 'todo-notes-app-debe3.firebaseapp.com',
    storageBucket: 'todo-notes-app-debe3.appspot.com',
    measurementId: 'G-54EXEC0PJ1',
  );
}
